var teams = [
	{ name: 'Baltimore Orioles', lat:39.283889 , long:-76.621667 , city: 'Baltimore', state:'MD', stadium: 'Oriole Park at Camden Yards', est: 1901, league:'American League', level:'MLB'},
	{ name: 'Boston Red Sox', lat:42.346389 , long:-71.0975 , city: 'Boston', state:'MA', stadium: 'Fenway Park', est: 1901, league:'American League', level:'MLB'},
	{ name: 'New York Yankees', lat:40.829167 , long:-73.926389 , city: 'New York', state:'NY', stadium: 'Yankee Stadium', est: 1903, league:'American League', level:'MLB'},
	{ name: 'Tampa Bay Rays', lat:27.768333 , long:-82.653333 , city: 'St. Petersburg', state:'FL', stadium: 'Tropicana Field', est: 1998, league:'American League', level:'MLB'},
	{ name: 'Toronto Blue Jays', lat:43.641389 , long:-79.389167 , city: 'Toronto', state:'ON', stadium: 'Rogers Centre', est: 1977, league:'American League', level:'MLB'},
	{ name: 'Chicago White Sox', lat:41.83 , long:-87.633889 , city: 'Chicago', state:'IL', stadium: 'U.S. Cellular Field', est: 1901, league:'American League', level:'MLB'},
	{ name: 'Cleveland Indians', lat:41.495833 , long:-81.685278 , city: 'Celevaland', state:'OH', stadium: 'Progressive Field', est: 1901, league:'American League', level:'MLB'},
	{ name: 'Detroit Tigers', lat:42.339167 , long:-83.048611 , city: 'Detroit', state:'MI', stadium: 'Comerica Park', est: 1901, league:'American League', level:'MLB'},
	{ name: 'Kansas City Royals', lat:39.051389 , long:-94.480556 , city: 'Kansas City', state:'MO', stadium: 'Kauffman Stadium', est: 1969, league:'American League', level:'MLB'},
	{ name: 'Minnesota Twins', lat:44.981667 , long:-93.278333 , city: 'Minneapolis', state:'MN', stadium: 'Target Field', est: 1901, league:'American League', level:'MLB'},
	{ name: 'Houston Astros', lat:29.756944 , long:-95.355556 , city: 'Houston', state:'TX', stadium: 'Minute Maid Park', est: 1962, league:'American League', level:'MLB'},
	{ name: 'Los Angeles Angels of Anaheim', lat:33.800278 , long:-117.882778 , city: 'Anaheim', stadium: 'Angel Stadium of Anaheim', state:'CA', est: 1961, league:'American League', level:'MLB'},
	{ name: 'Oakland Athletics', lat:37.751667 , long:-122.200556 , city: 'Oakland', state:'CA', stadium: 'O.co Coliseum', est: 1901, league:'American League', level:'MLB'},
	{ name: 'Seattle Mariners', lat:47.591389 , long:-122.3325 , city: 'Seattle', state:'WA', stadium: 'Safeco Field', est: 1977, league:'American League', level:'MLB'},
	{ name: 'Texas Rangers', lat:32.751389 , long:-97.082778 , city: 'Arlington', state:'TX', stadium: 'Globe Life Park in Arlington', est: 1961, league:'American League', level:'MLB'},

	{ name: 'Atlanta Braves', lat:33.735278 , long:-84.389444 , city: 'Atlanta', state:'GA', stadium: 'Turner Field', est: 1871, league:'National League', level:'MLB'},
	{ name: 'Miami Marlins', lat:25.778056 , long:-80.219722 , city: 'Miami', state:'FL', stadium: 'Marlins Park', est: 1993, league:'National League', level:'MLB'},
	{ name: 'New York Mets', lat:40.756944 , long:-73.845833 , city: 'New York', state:'NY', stadium: 'Citi Field', est: 1962, league:'National League', level:'MLB'},
	{ name: 'Philidelphia Phillies', lat:39.905833 , long:-75.166389 , city: 'Philidelphia', state:'PA', stadium: 'Citizens Bank Park', est: 1883, league:'National League', level:'MLB'},
	{ name: 'Washington Nationals', lat:38.872778 , long:-77.0075 , city: 'Washington', state:'D.C.', stadium: 'Nationals Park', est: 1969, league:'National League', level:'MLB'},
	{ name: 'Chicago Cubs', lat:41.948333 , long:-87.655556 , city: 'Chicago', state:'IL', stadium: 'Wrigley Field', est: 1870, league:'National League', level:'MLB'},
	{ name: 'Cincinnati Reds', lat:39.0975 , long:-84.506667 , city: 'Cincinnati', state:'OH', stadium: 'Great American Ball Park', est: 1882, league:'National League', level:'MLB'},
	{ name: 'Milwaukee Brewers', lat:43.028333 , long:-87.971111 , city: 'Milwaukee', state:'WI', stadium: 'Miller Park', est: 1969, league:'National League', level:'MLB'},
	{ name: 'Pittsburgh Pirates', lat:40.446944 , long:-80.005833 , city: 'Pittsburgh', state:'PA', stadium: 'PNC Park', est: 1882, league:'National League', level:'MLB'},
	{ name: 'St. Louis Cardinals', lat:38.6225 , long:-90.193056 , city: 'St. Louis', state:'MO', stadium: 'Busch Stadium', est: 1882, league:'National League', level:'MLB'},
	{ name: 'Arizona Diamondbacks', lat:33.445278 , long:-112.066944 , city: 'Phoenix', state:'AZ', stadium: 'Chase Field', est: 1998, league:'National League', level:'MLB'},
	{ name: 'Colorado Rockies', lat:39.756111 , long:-104.994167 , city: 'Denver', state:'CO', stadium: 'Coors Field', est: 1993, league:'National League', level:'MLB'},
	{ name: 'Los Angeles Dodgers', lat:34.073611 , long:-118.24 , city: 'Los Angeles', state:'CA', stadium: 'Dodger Stadium', est: 1884, league:'National League', level:'MLB'},
	{ name: 'San Diego Padres', lat:32.707222 , long:-117.156667 , city: 'San Diego', state:'CA', stadium: 'Petco Park', est: 1969, league:'National League', level:'MLB'},
	{ name: 'San Francisco Giants', lat:37.778611 , long:-122.389167 , city: 'San Francisco', state:'CA', stadium: 'AT&T Park', est: 1883, league:'National League', level:'MLB'},

/* AAA */
/* includes affiliation */
	{ name: 'Buffalo Bisons', affiliation:'Toronto Blue Jays' , league:'International League', level:'AAA'},
	{ name: 'Lehigh Valley IronPigs', affiliation:'Philidelphia Phillies' , league:'International League', level:'AAA'},
	{ name: 'Pawtucket Red Sox', affiliation:'Boston Red Sox' , league:'International League', level:'AAA'},
	{ name: 'Rochester Red Wings', affiliation:'Minnesota Twins' , league:'International League', level:'AAA'},
	{ name: 'Scranton/Wilkes-Barre RailRiders', affiliation:'New York Yankees' , league:'International League', level:'AAA'},
	{ name: 'Syracuse Chiefs', affiliation:'Washington Nationals' , league:'International League', level:'AAA'},
	{ name: 'Charlotte Knights', affiliation:'Chicago White Sox' , league:'International League', level:'AAA'},
	{ name: 'Durham Bulls', affiliation:'Tampa Bay Rays' , league:'International League', level:'AAA'},
	{ name: 'Gwinnett Braves', affiliation:'Atlanta Braves' , league:'International League', level:'AAA'},
	{ name: 'Norfolk Tides', affiliation:'Baltimore Orioles' , league:'International League', level:'AAA'},
	{ name: 'Columbus Clippers', affiliation:'Cleveland Indians' , league:'International League', level:'AAA'},
	{ name: 'Indianapolis Indians', affiliation:'Pittsburgh Pirates' , league:'International League', level:'AAA'},
	{ name: 'Louisville Bats', affiliation:'Cincinnati Reds' , league:'International League', level:'AAA'},
	{ name: 'Toledo Mud Hens', affiliation:'Detroit Tigers' , league:'International League', level:'AAA'},

	{ name: 'Colorado Springs Sky Sox', affiliation:'Milwaukee Brewers' , league:'Pacific Coast League', level:'AAA'},
	{ name: 'Iowa Cubs', affiliation:'Chicago Cubs' , league:'Pacific Coast League', level:'AAA'},
	{ name: 'Oklahoma City Dodgers', affiliation:'Los Angeles Dodgers' , league:'Pacific Coast League', level:'AAA'},
	{ name: 'Omaha Storm Chasers', affiliation:'Kansas City Royals' , league:'Pacific Coast League', level:'AAA'},
	{ name: 'Memphis Redbirds', affiliation:'St. Louis Cardinals' , league:'Pacific Coast League', level:'AAA'},
	{ name: 'Nashville Sounds', affiliation:'Oakland Athletics' , league:'Pacific Coast League', level:'AAA'},
	{ name: 'New Orleans Zephyrs', affiliation:'Miami Marlins' , league:'Pacific Coast League', level:'AAA'},
	{ name: 'Round Rock Express', affiliation:'Texas Rangers' , league:'Pacific Coast League', level:'AAA'},
	{ name: 'Fresno Grizzlies', affiliation:'Houston Astros' , league:'Pacific Coast League', level:'AAA'},
	{ name: 'Reno Aces', affiliation:'Arizona Diamondbacks' , league:'Pacific Coast League', level:'AAA'},
	{ name: 'Sacramento River Cats', affiliation:'San Francisco Giants' , league:'Pacific Coast League', level:'AAA'},
	{ name: 'Tacoma Rainiers', affiliation:'Seattle Mariners' , league:'Pacific Coast League', level:'AAA'},
	{ name: 'Alburquerque Isotopes', affiliation:'Colorado Rockies' , league:'Pacific Coast League', level:'AAA'},
	{ name: 'El Paso Chihuahuas', affiliation:'San Diego Padres' , league:'Pacific Coast League', level:'AAA'},
	{ name: 'Las Vegas 51s', affiliation:'New York Mets' , league:'Pacific Coast League', level:'AAA'},
	{ name: 'Salt Lake Bees', affiliation:'Los Angeles Angels of Anaheim' , league:'Pacific Coast League', level:'AAA'},

/* AA */
/* includes affiliation */
	{ name: 'Binghamton Mets', affiliation:'New York Mets' , league:'Eastern League', level:'AA'},
	{ name: 'New Britain Rock Cats', affiliation:'Coloradp Rockies' , league:'Eastern League', level:'AA'},
	{ name: 'New Hampshire Fisher Cats', affiliation:'Toronto Blue Jays' , league:'Eastern League', level:'AA'},
	{ name: 'Portland Sea Dogs', affiliation:'Boston Red Sox' , league:'Eastern League', level:'AA'},
	{ name: 'Reading Fightin Phils', affiliation:'Philidelphia Philles' , league:'Eastern League', level:'AA'},
	{ name: 'Trenton Thunder', affiliation:'New York Yankees' , league:'Eastern League', level:'AA'},
	{ name: 'Akron RubberDucks', affiliation:'Cleveland Indians' , league:'Eastern League', level:'AA'},
	{ name: 'Altoona Curve', affiliation:'Pittsburgh Pirates' , league:'Eastern League', level:'AA'},
	{ name: 'Bowie Baysox', affiliation:'Baltimore Orioles' , league:'Eastern League', level:'AA'},
	{ name: 'Erie SeaWolves', affiliation:'Detroit Tigers' , league:'Eastern League', level:'AA'},
	{ name: 'Harrisburg Senators', affiliation:'Washington Nationals' , league:'Eastern League', level:'AA'},
	{ name: 'Richmond Flying Squirrels', affiliation:'San Francisco Giants' , league:'Eastern League', level:'AA'},

	{ name: 'Birmingham Barons', affiliation:'Chicago White Sox' , league:'Southern League', level:'AA'},
	{ name: 'Chattanooga Lookouts', affiliation:'Minnesota Twins' , league:'Southern League', level:'AA'},
	{ name: 'Jackson Generals', affiliation:'Seattle Mariners' , league:'Southern League', level:'AA'},
	{ name: 'Montgomery Biscuits', affiliation:'Tampa Bay Rays' , league:'Southern League', level:'AA'},
	{ name: 'Tennessee Smokies', affiliation:'Chicago Cubs' , league:'Southern League', level:'AA'},
	{ name: 'South Biloxi Shuckers', affiliation:'Milwaukee Brewers' , league:'Southern League', level:'AA'},
	{ name: 'Jacksonville Suns', affiliation:'Miami Marlins' , league:'Southern League', level:'AA'},
	{ name: 'Mississippi Bravers', affiliation:'Atlanta Braves' , league:'Southern League', level:'AA'},
	{ name: 'Mobile BayBears', affiliation:'Arizona Diamondbacks' , league:'Southern League', level:'AA'},
	{ name: 'Pensacola Blue Wahoos', affiliation:'Cincinnati Reds' , league:'Southern League', level:'AA'},

	{ name: 'Arkansas Travelers', affiliation:'Los Angeles Angels of Anaheim' , league:'Texas League', level:'AA'},
	{ name: 'Northwest Arkansas Naturals', affiliation:'Kansas City Royals' , league:'Texas League', level:'AA'},
	{ name: 'Springfield Cardinals', affiliation:'St. Louis Cardinals' , league:'Texas League', level:'AA'},
	{ name: 'Tulsa Drillers', affiliation:'Los Angeles Dodgers' , league:'Texas League', level:'AA'},
	{ name: 'Corpus Christi Hooks', affiliation:'Houston Astros' , league:'Texas League', level:'AA'},
	{ name: 'Frisco RoughRiders',  affiliation:'Texas Rangers' , league:'Texas League', level:'AA'},
	{ name: 'Midland RockHounds', affiliation:'Oakland Athletics' , league:'Texas League', level:'AA'},
	{ name: 'San Antonio Missions', affiliation:'San Diego Padres' , league:'Texas League', level:'AA'},

/* A */
/* includes affiliation */
	{ name: 'Bakersfield Blaze', affiliation:'Seattle Mariners' , league:'California League', level:'A'},
	{ name: 'Modesto Nuts', affiliation:'Colorado Rockies' , league:'California League', level:'A'},
	{ name: 'San Jose Giants', affiliation:'San Francisco Giants' , league:'California League', level:'A'},
	{ name: 'Stockton Ports', affiliation:'Oakland Athletics' , league:'California League', level:'A'},
	{ name: 'Visalia Rawhide', affiliation:'Arizona Diamondbacks' , league:'California League', level:'A'},
	{ name: 'High Desert Mavericks', affiliation:'Texas Rangers' , league:'California League', level:'A'},
	{ name: 'Inland Empire 66ers', affiliation:'Los Angeles Angels of Anaheim' , league:'California League', level:'A'},
	{ name: 'Lake Elsinore Storm', affiliation:'San Diego Padres' , league:'California League', level:'A'},
	{ name: 'Lancaster JetHawks', affiliation:'Houston Astros' , league:'California League', level:'A'},
	{ name: 'Rancho Cucamonga Quakes', affiliation:'Los Angeles Dodgers' , league:'California League', level:'A'},

	{ name: 'Frederick Keys', affiliation:'Baltimore Orioles' , league:'Carolina League', level:'A'},
	{ name: 'Lynchburg Hillcats', affiliation:'Cleveland Indians' , league:'Carolina League', level:'A'},
	{ name: 'Potomac Nationals',  affiliation:'Washington Nationals' , league:'Carolina League', level:'A'},
	{ name: 'Wilmington Blue Rocks', affiliation:'Kansas City Royals' , league:'Carolina League', level:'A'},
	{ name: 'Carolina Mudcats', affiliation:'Atlanta Braves' , league:'Carolina League', level:'A'},
	{ name: 'Myrtle Beach Pelicans', affiliation:'Chicago Cubs' , league:'Carolina League', level:'A'},
	{ name: 'Salem Red Sox', affiliation:'Boston Red Sox' , league:'Carolina League', level:'A'},
	{ name: 'Winston-Salem Dash', affiliation:'Chicago White Sox' , league:'Carolina League', level:'A'},

	{ name: 'Brevard County Manatees', affiliation:'Milwaukee Brewers' , league:'Florida State League', level:'A'},
	{ name: 'Clearwater Threshers', affiliation:'Philidelphia Phillies' , league:'Florida State League', level:'A'},
	{ name: 'Daytona Tortugas', affiliation:'Cincinnati Reds' , league:'Florida State League', level:'A'},
	{ name: 'Dunedin Blue Jays', affiliation:'Toronto Blue Jays' , league:'Florida State League', level:'A'},
	{ name: 'Lakeland Flying Tigers', affiliation:'Detroit Tigers' , league:'Florida State League', level:'A'},
	{ name: 'Tampa Yankees', affiliation:'New York Yankees' , league:'Florida State League', level:'A'},
	{ name: 'Bradenton Marauders', affiliation:'Pittsburgh Pirates' , league:'Florida State League', level:'A'},
	{ name: 'Charlotte Stone Crabs' , affiliation:'Tampa Bay Rays' , league:'Florida State League', level:'A'},
	{ name: 'Fort Myers Miracle', affiliation:'Minnesota Twins' , league:'Florida State League', level:'A'},
	{ name: 'Jupiter Hammerheads', affiliation:'Miami Marlins' , league:'Florida State League', level:'A'},
	{ name: 'Palm Beach Cardinals' , affiliation:'St. Louis Cardinals' , league:'Florida State League', level:'A'},
	{ name: 'St. Lucie Mets', affiliation:'New York Mets' , league:'Florida State League', level:'A'},

	{ name: 'Bowling Green Hot Rods', affiliation:'Tampa Bay Rays' , league:'Midwest League', level:'A'},
	{ name: 'Dayton Dragons', affiliation:'Cincinnati Reds' , league:'Midwest League', level:'A'},
	{ name: 'Fort Wayne TinCaps', affiliation:'San Diego Padres' , league:'Midwest League', level:'A'},
	{ name: 'Great Lakes Loons', affiliation:'Los Angeles Dodgers' , league:'Midwest League', level:'A'},
	{ name: 'Lake County Captains', affiliation:'Cleveland Indians' , league:'Midwest League', level:'A'},
	{ name: 'Lansing Lugnuts', affiliation:'Toronto Blue Jays' , league:'Midwest League', level:'A'},
	{ name: 'South Bend Cubs', affiliation:'Chicago Cubs' , league:'Midwest League', level:'A'},
	{ name: 'West Michigan Whitecaps', affiliation:'Detroit Tigers' , league:'Midwest League', level:'A'},
	{ name: 'Beloit Snappers', affiliation:'Oakland Athletics' , league:'Midwest League', level:'A'},
	{ name: 'Burlington Bees', affiliation:'Los Angeles Angels of Anaheim' , league:'Midwest League', level:'A'},
	{ name: 'Cedar Rapids Kernels', affiliation:'Minnesota Twins' , league:'Midwest League', level:'A'},
	{ name: 'Clinton LumberKings', affiliation:'Seattle Mariners' , league:'Midwest League', level:'A'},
	{ name: 'Kane County Cougars', affiliation:'Arizona Diamondbacks' , league:'Midwest League', level:'A'},
	{ name: 'Peoria Chiefs', affiliation:'St. Louis Cardinals' , league:'Midwest League', level:'A'},
	{ name: 'Quad Cities River Bandits', affiliation:'Houston Astros' , league:'Midwest League', level:'A'},
	{ name: 'Wisconsin Timber Rattlers', affiliation:'Milwaukee Brewers' , league:'Midwest League', level:'A'},

	{ name: 'Delmarva Shorebirds', affiliation:'Baltimore Orioles' , league:'South Atlantic League', level:'A'},
	{ name: 'Greensboro Grasshoppers', affiliation:'Miami Marlins' , league:'South Atlantic League', level:'A'},
	{ name: 'Hagerstown Suns', affiliation:'Washington Nationals' , league:'South Atlantic League', level:'A'},
	{ name: 'Hickory Crawdads', affiliation:'Texas Rangers' , league:'South Atlantic League', level:'A'},
	{ name: 'Kannapolis Intimidators', affiliation:'Chicago White Sox' , league:'South Atlantic League', level:'A'},
	{ name: 'Lakewood BlueClaws', affiliation:'Philidelphia Phillies' , league:'South Atlantic League', level:'A'},
	{ name: 'West Virginia Power', affiliation:'Pittsburgh Pirates' , league:'South Atlantic League', level:'A'},
	{ name: 'Asheville Tourists', affiliation:'Colorado Rockies' , league:'South Atlantic League', level:'A'},
	{ name: 'Augusta GreenJackets', affiliation:'San Francsisco Giants' , league:'South Atlantic League', level:'A'},
	{ name: 'Charleston RiverDogs', affiliation:'New York Yankees' , league:'South Atlantic League', level:'A'},
	{ name: 'Greenville Drive', affiliation:'Boston Red Sox' , league:'South Atlantic League', level:'A'},
	{ name: 'Lexington Legends', affiliation:'Kansas City Royals' , league:'South Atlantic League', level:'A'},
	{ name: 'Rome Braves', affiliation:'Atlanta Braves' , league:'South Atlantic League', level:'A'},
	{ name: 'Savannah Sand Gnats', affiliation:'New York Mets' , league:'South Atlantic League', level:'A'},

	{ name: 'Aberdeen IronBirds', affiliation:'Baltimore Orioles' , league:'New York-Penn League', level:'A'},
	{ name: 'Brooklyn Cyclones', affiliation:'New York Mets' , league:'New York-Penn League', level:'A'},
	{ name: 'Hudson Valley Renegades', affiliation:'Tampa Bay Rays' , league:'New York-Penn League', level:'A'},
	{ name: 'Staten Island Yankees', affiliation:'New York Yankees' , league:'New York-Penn League', level:'A'},
	{ name: 'Auburn Doubledays', affiliation:'Washington Nationals' , league:'New York-Penn League', level:'A'},
	{ name: 'Batavia Muckdogs', affiliation:'Miami Marlins' , league:'New York-Penn League', level:'A'},
	{ name: 'Mahoning Valley Scrappers', affiliation:'Cleveland Indians' , league:'New York-Penn League', level:'A'},
	{ name: 'State College Spikes', affiliation:'St. Louis Cardinals' , league:'New York-Penn League', level:'A'},
	{ name: 'West Virginia Black Bears', affiliation:'Pittsburgh Pirates' , league:'New York-Penn League', level:'A'},
	{ name: 'Williamsport Crosscutters', affiliation:'Philidelphia Phillies' , league:'New York-Penn League', level:'A'},
	{ name: 'Connecticut Tigers', affiliation:'Detroit Tigers' , league:'New York-Penn League', level:'A'},
	{ name: 'Lowell Spinners', affiliation:'Boston Red Sox' , league:'New York-Penn League', level:'A'},
	{ name: 'Tri-City ValleyCats', affiliation:'Houston Astros' , league:'New York-Penn League', level:'A'},
	{ name: 'Vermont Lake Monsters', affiliation:'Oakland Athletics' , league:'New York-Penn League', level:'A'},

	{ name: 'Everett AquaSox', affiliation:'Seattle Mariners' , league:'Northwest League', level:'A'},
	{ name: 'Spokane Indians', affiliation:'Texas Rangers' , league:'Northwest League', level:'A'},
	{ name: 'Tri-City Dust Devils', affiliation:'San Diego Padres' , league:'Northwest League', level:'A'},
	{ name: 'Vancouver Canadians', affiliation:'Toronto Blue Jays' , league:'Northwest League', level:'A'},
	{ name: 'South Boise Hawks', affiliation:'Colorado Rockies' , league:'Northwest League', level:'A'},
	{ name: 'Eugene Emeralds', affiliation:'Chicago Cubs' , league:'Northwest League', level:'A'},
	{ name: 'Hillsboro Hops', affiliation:'Arizona Diamondbacks' , league:'Northwest League', level:'A'},
	{ name: 'Salem-Keizer Volcanoes', affiliation:'San Francisco Giants' , league:'Northwest League', level:'A'},

	{ name: 'Bluefield Blue Jays', affiliation:'Toronto Blue Jays' , league:'Appalachian League', level:'Rookie'},
	{ name: 'Burlington Royals', affiliation:'Kansas City Royals' , league:'Appalachian League', level:'Rookie'},
	{ name: 'Danville Braves', affiliation:'Atlanta Braves' , league:'Appalachian League', level:'Rookie'},
	{ name: 'Princeton Rays', affiliation:'Tampa Bay Rays' , league:'Appalachian League', level:'Rookie'},
	{ name: 'Pulaski Yankees', affiliation:'New York Yankees' , league:'Appalachian League', level:'Rookie'},
	{ name: 'Bristol Pirates', affiliation:'Pittsburgh Pirates' , league:'Appalachian League', level:'Rookie'},
	{ name: 'Elizabethton Twins', affiliation:'Minnesota Twins' , league:'Appalachian League', level:'Rookie'},
	{ name: 'Greeneville Astros', affiliation:'Houston Astros' , league:'Appalachian League', level:'Rookie'},
	{ name: 'Johnson City Cardinals', affiliation:'St. Louis Cardinals' , league:'Appalachian League', level:'Rookie'},
	{ name: 'Kingsport Mets', affiliation:'New York Mets' , league:'Appalachian League', level:'Rookie'},

	{ name: 'Billings Mustangs', affiliation:'Cincinnati Reds' , league:'Pioneer League', level:'Rookie'},
	{ name: 'Great Falls Voyagers', affiliation:'Chicago White Sox' , league:'Pioneer League', level:'Rookie'},
	{ name: 'Helena Brewers', affiliation:'Milwaukee Brewers' , league:'Pioneer League', level:'Rookie'},
	{ name: 'Missoula Osprey', affiliation:'Arizona Diamondbacks' , league:'Pioneer League', level:'Rookie'},
	{ name: 'Grand Junction Rockies', affiliation:'Colorado Rockies' , league:'Pioneer League', level:'Rookie'},
	{ name: 'Idaho Falls Chukars', affiliation:'Kansas City Royals' , league:'Pioneer League', level:'Rookie'},
	{ name: 'Ogden Raptors', affiliation:'Los Angeles Dodgers' , league:'Pioneer League', level:'Rookie'},
	{ name: 'Orem Owlz', affiliation:'Los Angeles Angels of Anaheim' , league:'Pioneer League', level:'Rookie'},

	{ name: 'Arizona League Angels', affiliation:'Los Angeles Angels of Anaheim' , league:'Arizona League', level:'Rookie'},
	{ name: 'Arizona League Athletics', affiliation:'Oakland Athletics' , league:'Arizona League', level:'Rookie'},
	{ name: 'Arizona League Brewers', affiliation:'Milwaukee Brewers' , league:'Arizona League', level:'Rookie'},
	{ name: 'Arizona League Cubs', affiliation:'Chicago Cubs' , league:'Arizona League', level:'Rookie'},
	{ name: 'Arizona League Diamondbacks', affiliation:'Arizona Diamondbacks' , league:'Arizona League', level:'Rookie'},
	{ name: 'Arizona League Dodgers', affiliation:'Los Angeles Dodgers' , league:'Arizona League', level:'Rookie'},
	{ name: 'Arizona League Giants', affiliation:'San Francisco Giants' , league:'Arizona League', level:'Rookie'},
	{ name: 'Arizona League Indians', affiliation:'Cleveland Indians' , league:'Arizona League', level:'Rookie'},
	{ name: 'Arizona League Mariners', affiliation:'Seattle Mariners' , league:'Arizona League', level:'Rookie'},
	{ name: 'Arizona League Padres', affiliation:'San Diego Padres' , league:'Arizona League', level:'Rookie'},
	{ name: 'Arizona League Rangers', affiliation:'Texas Rangers' , league:'Arizona League', level:'Rookie'},
	{ name: 'Arizona League Reds', affiliation:'Cincinnati Reds' , league:'Arizona League', level:'Rookie'},
	{ name: 'Arizona League Royals', affiliation:'Kansas City Royals' , league:'Arizona League', level:'Rookie'},
	{ name: 'Arizona League White Sox', affiliation:'Chicago White Sox' , league:'Arizona League', level:'Rookie'},

	{ name: 'GCL Cardinals', affiliation:'St. Louis Cardinals' , league:'Gulf Coast League', level:'Rookie'},
	{ name: 'GCL Marlins', affiliation:'Miami Marlins' , league:'Gulf Coast League', level:'Rookie'},
	{ name: 'GCL Mets', affiliation:'New York Mets' , league:'Gulf Coast League', level:'Rookie'},
	{ name: 'GCL Nationals', affiliation:'Washington National' , league:'Gulf Coast League', level:'Rookie'},
	{ name: 'GCL Astros', affiliation:'Houston Astros' , league:'Gulf Coast League', level:'Rookie'},
	{ name: 'GCL Braves', affiliation:'Atlanta Braves' , league:'Gulf Coast League', level:'Rookie'},
	{ name: 'GCL Tigers', affiliation:'Detroit Tigers' , league:'Gulf Coast League', level:'Rookie'},
	{ name: 'GCL Yankees 2', affiliation:'New York Yankees' , league:'Gulf Coast League', level:'Rookie'},
	{ name: 'GCL Blue Jays', affiliation:'Toronto Blue Jays' , league:'Gulf Coast League', level:'Rookie'},
	{ name: 'GCL Phillies', affiliation:'Philadelphia Phillies' , league:'Gulf Coast League', level:'Rookie'},
	{ name: 'GCL Pirates', affiliation:'Pittsburgh Pirates' , league:'Gulf Coast League', level:'Rookie'},
	{ name: 'GCL Yankees 1', affiliation:'New York Yankees' , league:'Gulf Coast League', level:'Rookie'},
	{ name: 'GCL Orioles', affiliation:'Baltimore Orioles' , league:'Gulf Coast League', level:'Rookie'},
	{ name: 'GCL Rays', affiliation:'Tampa Bay Rays' , league:'Gulf Coast League', level:'Rookie'},
	{ name: 'GCL Red Sox', affiliation:'Boston Red Sox' , league:'Gulf Coast League', level:'Rookie'},
	{ name: 'GCL Twins', affiliation:'Minnesota Twins' , league:'Gulf Coast League', level:'Rookie'},

];