/* DATA SECTION */

/* MAJOR LEAGUE BASEBALL */
var teams = [
	{ name: 'Baltimore Orioles', lat:39.283889 , long:-76.621667 , city: 'Baltimore', state:'MD', stadium: 'Oriole Park at Camden Yards', est: 1901, league:'American League', level:'MLB'},
	{ name: 'Boston Red Sox', lat:42.346389 , long:-71.0975 , city: 'Boston', state:'MA', stadium: 'Fenway Park', est: 1901, league:'American League', level:'MLB'},
	{ name: 'New York Yankees', lat:40.829167 , long:-73.926389 , city: 'New York', state:'NY', stadium: 'Yankee Stadium', est: 1903, league:'American League', level:'MLB'},
	{ name: 'Tampa Bay Rays', lat:27.768333 , long:-82.653333 , city: 'St. Petersburg', state:'FL', stadium: 'Tropicana Field', est: 1998, league:'American League', level:'MLB'},
	{ name: 'Toronto Blue Jays', lat:43.641389 , long:-79.389167 , city: 'Toronto', state:'ON', stadium: 'Rogers Centre', est: 1977, league:'American League', level:'MLB'},
	{ name: 'Chicago White Sox', lat:41.83 , long:-87.633889 , city: 'Chicago', state:'IL', stadium: 'U.S. Cellular Field', est: 1901, league:'American League', level:'MLB'},
	{ name: 'Cleveland Indians', lat:41.495833 , long:-81.685278 , city: 'Celevaland', state:'OH', stadium: 'Progressive Field', est: 1901, league:'American League', level:'MLB'},
	{ name: 'Detroit Tigers', lat:42.339167 , long:-83.048611 , city: 'Detroit', state:'MI', stadium: 'Comerica Park', est: 1901, league:'American League', level:'MLB'},
	{ name: 'Kansas City Royals', lat:39.051389 , long:-94.480556 , city: 'Kansas City', state:'MO', stadium: 'Kauffman Stadium', est: 1969, league:'American League', level:'MLB'},
	{ name: 'Minnesota Twins', lat:44.981667 , long:-93.278333 , city: 'Minneapolis', state:'MN', stadium: 'Target Field', est: 1901, league:'American League', level:'MLB'},
	{ name: 'Houston Astros', lat:29.756944 , long:-95.355556 , city: 'Houston', state:'TX', stadium: 'Minute Maid Park', est: 1962, league:'American League', level:'MLB'},
	{ name: 'Los Angeles Angels of Anaheim', lat:33.800278 , long:-117.882778 , city: 'Anaheim', stadium: 'Angel Stadium of Anaheim', state:'CA', est: 1961, league:'American League', level:'MLB'},
	{ name: 'Oakland Athletics', lat:37.751667 , long:-122.200556 , city: 'Oakland', state:'CA', stadium: 'O.co Coliseum', est: 1901, league:'American League', level:'MLB'},
	{ name: 'Seattle Mariners', lat:47.591389 , long:-122.3325 , city: 'Seattle', state:'WA', stadium: 'Safeco Field', est: 1977, league:'American League', level:'MLB'},
	{ name: 'Texas Rangers', lat:32.751389 , long:-97.082778 , city: 'Arlington', state:'TX', stadium: 'Globe Life Park in Arlington', est: 1961, league:'American League', level:'MLB'},

	{ name: 'Atlanta Braves', lat:33.735278 , long:-84.389444 , city: 'Atlanta', state:'GA', stadium: 'Turner Field', est: 1871, league:'National League', level:'MLB'},
	{ name: 'Miami Marlins', lat:25.778056 , long:-80.219722 , city: 'Miami', state:'FL', stadium: 'Marlins Park', est: 1993, league:'National League', level:'MLB'},
	{ name: 'New York Mets', lat:40.756944 , long:-73.845833 , city: 'New York', state:'NY', stadium: 'Citi Field', est: 1962, league:'National League', level:'MLB'},
	{ name: 'Philidelphia Phillies', lat:39.905833 , long:-75.166389 , city: 'Philidelphia', state:'PA', stadium: 'Citizens Bank Park', est: 1883, league:'National League', level:'MLB'},
	{ name: 'Washington Nationals', lat:38.872778 , long:-77.0075 , city: 'Washington', state:'D.C.', stadium: 'Nationals Park', est: 1969, league:'National League', level:'MLB'},
	{ name: 'Chicago Cubs', lat:41.948333 , long:-87.655556 , city: 'Chicago', state:'IL', stadium: 'Wrigley Field', est: 1870, league:'National League', level:'MLB'},
	{ name: 'Cincinnati Reds', lat:39.0975 , long:-84.506667 , city: 'Cincinnati', state:'OH', stadium: 'Great American Ball Park', est: 1882, league:'National League', level:'MLB'},
	{ name: 'Milwaukee Brewers', lat:43.028333 , long:-87.971111 , city: 'Milwaukee', state:'WI', stadium: 'Miller Park', est: 1969, league:'National League', level:'MLB'},
	{ name: 'Pittsburgh Pirates', lat:40.446944 , long:-80.005833 , city: 'Pittsburgh', state:'PA', stadium: 'PNC Park', est: 1882, league:'National League', level:'MLB'},
	{ name: 'St. Louis Cardinals', lat:38.6225 , long:-90.193056 , city: 'St. Louis', state:'MO', stadium: 'Busch Stadium', est: 1882, league:'National League', level:'MLB'},
	{ name: 'Arizona Diamondbacks', lat:33.445278 , long:-112.066944 , city: 'Phoenix', state:'AZ', stadium: 'Chase Field', est: 1998, league:'National League', level:'MLB'},
	{ name: 'Colorado Rockies', lat:39.756111 , long:-104.994167 , city: 'Denver', state:'CO', stadium: 'Coors Field', est: 1993, league:'National League', level:'MLB'},
	{ name: 'Los Angeles Dodgers', lat:34.073611 , long:-118.24 , city: 'Los Angeles', state:'CA', stadium: 'Dodger Stadium', est: 1884, league:'National League', level:'MLB'},
	{ name: 'San Diego Padres', lat:32.707222 , long:-117.156667 , city: 'San Diego', state:'CA', stadium: 'Petco Park', est: 1969, league:'National League', level:'MLB'},
	{ name: 'San Francisco Giants', lat:37.778611 , long:-122.389167 , city: 'San Francisco', state:'CA', stadium: 'AT&T Park', est: 1883, league:'National League', level:'MLB'},

/* AAA */
/* includes affiliation */
	{ name: 'Buffalo Bisons', lat:42.883333 , long:-78.866667 , city: 'Buffalo', state:'NY', stadium: 'Coca-Cola Field', est:1979 , affiliation:'Toronto Blue Jays' , league:'International League', level:'AAA'},
	{ name: 'Lehigh Valley IronPigs', lat:40.626111 , long:-75.4525 , city: 'Allentown', state:'PA', stadium: 'Coca-Cola Park', est:1993 , affiliation:'Philidelphia Phillies' , league:'International League', level:'AAA'},
	{ name: 'Pawtucket Red Sox', lat:41.873164 , long:-71.370039 , city: 'Pawtucket', state:'RI', stadium: 'McCoy Stadium', est:1970 , affiliation:'Boston Red Sox' , league:'International League', level:'AAA'},
	{ name: 'Rochester Red Wings', lat:43.158267 , long:-77.619794 , city: 'Rochester', state:'NY', stadium: 'Frontier Field', est:1886 , affiliation:'Minnesota Twins' , league:'International League', level:'AAA'},
	{ name: 'Scranton/Wilkes-Barre RailRiders', lat:41.360406 , long:-75.683967 , city: 'Moosic', state:'PA', stadium: 'PNC Field', est:1919 , affiliation:'New York Yankees' , league:'International League', level:'AAA'},
	{ name: 'Syracuse Chiefs', lat:43.079078 , long:-76.165358 , city: 'Syracuse', state:'NY', stadium: 'NBT Bank Stadium', est:1934 , affiliation:'Washington Nationals' , league:'International League', level:'AAA'},
	{ name: 'Charlotte Knights', lat:35.227988 , long:-80.849011 , city: 'Charlotte', state:'NC', stadium: 'BB&T Ballpark', est:1976 , affiliation:'Chicago White Sox' , league:'International League', level:'AAA'},
	{ name: 'Durham Bulls', lat:35.991689 , long:-78.904186 , city: 'Durham', state:'NC', stadium: 'Durham Bulls Athletic Park', est:1902 , affiliation:'Tampa Bay Rays' , league:'International League', level:'AAA'},
	{ name: 'Gwinnett Braves', lat:34.041494 , long:-83.992367 , city: 'Lawrenceville', state:'GA', stadium: 'Coolray Field', est:1901 , affiliation:'Atlanta Braves' , league:'International League', level:'AAA'},
	{ name: 'Norfolk Tides', lat:36.842789 , long:-76.278869 , city: 'Norfolk', state:'VA', stadium: 'Harbor Park', est:1961 , affiliation:'Baltimore Orioles' , league:'International League', level:'AAA'},
	{ name: 'Columbus Clippers', lat:39.968619 , long:-83.010743 , city: 'Columbus', state:'OH', stadium: 'Huntington Park', est:1977 , affiliation:'Cleveland Indians' , league:'International League', level:'AAA'},
	{ name: 'Indianapolis Indians', lat:39.765 , long:-86.168333 , city: 'Indianapolis', state:'IN', stadium: 'Victory Field', est:1902 , affiliation:'Pittsburgh Pirates' , league:'International League', level:'AAA'},
	{ name: 'Louisville Bats', lat:38.256186 , long:-85.744653 , city: 'Louisville', state:'KY', stadium: 'Louisville Slugger Field', est:1966 , affiliation:'Cincinnati Reds' , league:'International League', level:'AAA'},
	{ name: 'Toledo Mud Hens', lat:41.648314 , long:-83.538986 , city: 'Toledo', state:'OH', stadium: 'Fifth Third Field', est:1883 , affiliation:'Detroit Tigers' , league:'International League', level:'AAA'},

	{ name: 'Colorado Springs Sky Sox', lat:38.894172 , long:-104.710311 , city: 'Colorado Springs', state:'CO', stadium: 'Security Service Field', est:1988 , affiliation:'Milwaukee Brewers' , league:'Pacific Coast League', level:'AAA'},
	{ name: 'Iowa Cubs', lat:41.580278 , long:-93.615833 , city: 'Des Moines', state:'IO', stadium: 'Principal Park', est:1969 , affiliation:'Chicago Cubs' , league:'Pacific Coast League', level:'AAA'},
	{ name: 'Oklahoma City Dodgers', lat:35.464961 , long:-97.50805 , city: 'Oklahoma City', state:'OK', stadium: 'Chicksaw Bricktown Ballpark', est:1962 , affiliation:'Los Angeles Dodgers' , league:'Pacific Coast League', level:'AAA'},
	{ name: 'Omaha Storm Chasers', lat:41.151 , long:-96.107 , city: 'Papillion', state:'NE', stadium: 'Werner Park', est:1969 , affiliation:'Kansas City Royals' , league:'Pacific Coast League', level:'AAA'},
	{ name: 'Memphis Redbirds', lat:35.143056 , long:-90.049167 , city: 'Memphis', state:'TN', stadium: 'AutoZone Park', est:1998 , affiliation:'St. Louis Cardinals' , league:'Pacific Coast League', level:'AAA'},
	{ name: 'Nashville Sounds', lat:36.173031 , long:-86.785033 , city: 'Nashville', state:'TN', stadium: 'First Tennesse Park', est:1978 , affiliation:'Oakland Athletics' , league:'Pacific Coast League', level:'AAA'},
	{ name: 'New Orleans Zephyrs', lat:29.975442 , long:-90.199742 , city: 'Metairie', state:'LA', stadium: 'Zephyr Field', est:1993 , affiliation:'Miami Marlins' , league:'Pacific Coast League', level:'AAA'},
	{ name: 'Round Rock Express', lat:30.5273 , long:-97.6305 , city: 'Round Rock', state:'TX', stadium: 'Dell Diamond', est:1979 , affiliation:'Texas Rangers' , league:'Pacific Coast League', level:'AAA'},
	{ name: 'Fresno Grizzlies', lat:36.7321 , long:-119.7905 , city: 'Fresno', state:'CA', stadium: 'Chukchansi Park', est:1998 , affiliation:'Houston Astros' , league:'Pacific Coast League', level:'AAA'},
	{ name: 'Reno Aces', lat:39.528131 , long:-119.808633 , city: 'Reno', state:'NV', stadium: 'Aces Ballpark', est:2009 , affiliation:'Arizona Diamondbacks' , league:'Pacific Coast League', level:'AAA'},
	{ name: 'Sacramento River Cats', lat:38.580372 , long:-121.5138 , city: 'Sacramento', state:'CA', stadium: 'Raley Field', est:1978 , affiliation:'San Francisco Giants' , league:'Pacific Coast League', level:'AAA'},
	{ name: 'Tacoma Rainiers', lat:47.238033 , long:-122.497544 , city: 'Tacoma', state:'WA', stadium: 'Cheney Stadium', est:1960 , affiliation:'Seattle Mariners' , league:'Pacific Coast League', level:'AAA'},
	{ name: 'Alburquerque Isotopes', lat:35.069722 , long:-106.629167 , city: 'Alburquerque', state:'NM', stadium: 'Isotopes Park', est:2003 , affiliation:'Colorado Rockies' , league:'Pacific Coast League', level:'AAA'},
	{ name: 'El Paso Chihuahuas', lat:31.7590901 , long:-106.4896401 , city: 'El Paso', state:'TX', stadium: 'Southwest University Park', est:2014 , affiliation:'San Diego Padres' , league:'Pacific Coast League', level:'AAA'},
	{ name: 'Las Vegas 51s', lat:36.179667 , long:-115.129972 , city: 'Las Vegas', state:'NV', stadium: 'Cashman Field', est:1919 , affiliation:'New York Mets' , league:'Pacific Coast League', level:'AAA'},
	{ name: 'Salt Lake Bees', lat:40.740556 , long:-111.892778 , city: 'Salt Lake City', state:'UT', stadium: "Smith's BallPark", est:1994 , affiliation:'Los Angeles Angels of Anaheim' , league:'Pacific Coast League', level:'AAA'},

/* AA */
/* includes affiliation */
	{ name: 'Binghamton Mets', lat:42.102769 , long:-75.904988 , city: 'Binghamton', state:'NY', stadium: 'NYSEG Stadium', est:1987 , affiliation:'New York Mets' , league:'Eastern League', level:'AA'},
	{ name: 'New Britain Rock Cats', lat:41.648506 , long:-72.775211 , city: 'New Britain', state:'CT', stadium: 'New Britain Stadum', est:1983 , affiliation:'Coloradp Rockies' , league:'Eastern League', level:'AA'},
	{ name: 'New Hampshire Fisher Cats', lat:42.980833 , long:-71.466667 , city: 'Manchester', state:'NH', stadium: 'Delta Dental Stadium', est:1994 , affiliation:'Toronto Blue Jays' , league:'Eastern League', level:'AA'},
	{ name: 'Portland Sea Dogs', lat:43.656944 , long:-70.278333 , city: 'Portland', state:'ME', stadium: 'Hadlock Field', est:1994 , affiliation:'Boston Red Sox' , league:'Eastern League', level:'AA'},
	{ name: 'Reading Fightin Phils', lat:40.365833 , long:-75.933611 , city: 'Reading', state:'PA', stadium: 'FirstEnergy Stadium', est:1967 , affiliation:'Philidelphia Philles' , league:'Eastern League', level:'AA'},
	{ name: 'Trenton Thunder', lat:40.2037395 , long:-74.7612495 , city: 'Trenton', state:'NJ', stadium: 'Arm & Hammer Park', est:1980 , affiliation:'New York Yankees' , league:'Eastern League', level:'AA'},
	{ name: 'Akron RubberDucks', lat:41.077924 , long:-81.522202 , city: 'Akron', state:'OH', stadium: 'Canal Park', est:1980 , affiliation:'Cleveland Indians' , league:'Eastern League', level:'AA'},
	{ name: 'Altoona Curve', lat:40.473611 , long:-78.394722 , city: 'Altoona', state:'PA', stadium: 'Peoples Natural Gas Field', est:1998 , affiliation:'Pittsburgh Pirates' , league:'Eastern League', level:'AA'},
	{ name: 'Bowie Baysox', lat:38.945556 , long:-76.709167 , city: 'Bowie', state:'MD', stadium: "Prince George's Stadium", est:1993 , affiliation:'Baltimore Orioles' , league:'Eastern League', level:'AA'},
	{ name: 'Erie SeaWolves', lat:42.126944 , long:-80.08 , city: 'Erie', state:'PA', stadium: 'Jerry Uht Park', est:1989 , affiliation:'Detroit Tigers' , league:'Eastern League', level:'AA'},
	{ name: 'Harrisburg Senators', lat:40.256428 , long:-76.889977 , city: 'Harrisburg', state:'PA', stadium: 'Metro Bank', est:1987 , affiliation:'Washington Nationals' , league:'Eastern League', level:'AA'},
	{ name: 'Richmond Flying Squirrels', lat:37.571806 , long:-77.463733 , city: 'Richmond', state:'VA', stadium: 'The Diamond', est:1972 , affiliation:'San Francisco Giants' , league:'Eastern League', level:'AA'},

	{ name: 'Birmingham Barons', lat:33.50763 , long:-86.810218 , city: 'Birmingham', state:'AL', stadium: 'Regions Field', est:1885 , affiliation:'Chicago White Sox' , league:'Southern League', level:'AA'},
	{ name: 'Chattanooga Lookouts', lat:35.054444 , long:-85.313889 , city: 'Chattanooga', state:'TN', stadium: 'AT&T Field', est:1885 , affiliation:'Minnesota Twins' , league:'Southern League', level:'AA'},
	{ name: 'Jackson Generals', lat:35.676192 , long:-88.769303 , city: 'Jackson', state:'TN', stadium: 'The Ballpark at Jackson', est:1998 , affiliation:'Seattle Mariners' , league:'Southern League', level:'AA'},
	{ name: 'Montgomery Biscuits', lat:32.3822 , long:-86.3106 , city: 'Montgomery', state:'AL', stadium: 'Riverwalk Stadium', est:1973 , affiliation:'Tampa Bay Rays' , league:'Southern League', level:'AA'},
	{ name: 'Tennessee Smokies', lat:35.988889 , long:-83.604444 , city: 'Kodak', state:'TN', stadium: 'Smokies Park', est:1897 , affiliation:'Chicago Cubs' , league:'Southern League', level:'AA'},
	{ name: 'South Biloxi Shuckers', lat:30.395741 , long:-88.893463 , city: 'Biloxi', state:'MS', stadium: 'MGM Park', est:2015 , affiliation:'Milwaukee Brewers' , league:'Southern League', level:'AA'},
	{ name: 'Jacksonville Suns', lat:30.324968 , long:-81.643069 , city: 'Jacksonville', state:'FL', stadium: 'Grounds of Jacksonville', est:1962 , affiliation:'Miami Marlins' , league:'Southern League', level:'AA'},
	{ name: 'Mississippi Bravers', lat:32.27391 , long:-90.147969 , city: 'Pearl', state:'MS', stadium: 'Trustmark Park', est:2005 , affiliation:'Atlanta Braves' , league:'Southern League', level:'AA'},
	{ name: 'Mobile BayBears', lat:30.64574 , long:-88.11687 , city: 'Mobile', state:'AL', stadium: 'Hank Aaron Stadium', est:1976 , affiliation:'Arizona Diamondbacks' , league:'Southern League', level:'AA'},
	{ name: 'Pensacola Blue Wahoos', lat:30.404295 , long:-87.219662 , city: 'Pensacola', state:'FL', stadium: 'Pensacola Bayfront Stadium', est:1959 , affiliation:'Cincinnati Reds' , league:'Southern League', level:'AA'},

	{ name: 'Arkansas Travelers', lat:34.755215 , long:-92.272582 , city: 'North Little Rock', state:'AR', stadium: 'Dickey-Stephens Park', est:1963 , affiliation:'Los Angeles Angels of Anaheim' , league:'Texas League', level:'AA'},
	{ name: 'Northwest Arkansas Naturals', lat:36.159167 , long:-94.195 , city: 'Springdale', state:'AR', stadium: 'Arvest Ballpark', est:2008 , affiliation:'Kansas City Royals' , league:'Texas League', level:'AA'},
	{ name: 'Springfield Cardinals', lat:37.2105726 , long:-93.2801087 , city: 'Springfield', state:'MO', stadium: 'Hammons Field', est:2005 , affiliation:'St. Louis Cardinals' , league:'Texas League', level:'AA'},
	{ name: 'Tulsa Drillers', lat:36.159722 , long:-95.988056 , city: 'Tulsa', state:'OK', stadium: 'ONEOK Field', est:1977 , affiliation:'Los Angeles Dodgers' , league:'Texas League', level:'AA'},
	{ name: 'Corpus Christi Hooks', lat:27.809583 , long:-97.399694 , city: 'Corpus Christi', state:'TX', stadium: 'Whataburger Field', est:1968 , affiliation:'Houston Astros' , league:'Texas League', level:'AA'},
	{ name: 'Frisco RoughRiders', lat:33.098382 , long:-96.81972 , city: 'Frisco', state:'TX', stadium: 'Dr. Pepper Ballpark', est:2003 , affiliation:'Texas Rangers' , league:'Texas League', level:'AA'},
	{ name: 'Midland RockHounds', lat:31.987332 , long:-102.155799 , city: 'Midland', state:'TX', stadium: 'Security Bank Ballpark', est:1972 , affiliation:'Oakland Athletics' , league:'Texas League', level:'AA'},
	{ name: 'San Antonio Missions', lat:29.409131 , long:-98.601114 , city: 'San Antonio', state:'TX', stadium: 'Nelson W. Wolff Municipal Stadium', est:1888 , affiliation:'San Diego Padres' , league:'Texas League', level:'AA'},

/* A */
/* includes affiliation */
	{ name: 'Bakersfield Blaze', lat:35.397556 , long:-119.022384 , city: 'Bakersfield', state:'CA', stadium: 'Sam Lynn Ballpark', est:1941 , affiliation:'Seattle Mariners' , league:'California League', level:'A'},
	{ name: 'Modesto Nuts', lat:37.622658 , long:-121.000814 , city: 'Modesto', state:'CA', stadium: 'John Thurman Field', est:1946 , affiliation:'Colorado Rockies' , league:'California League', level:'A'},
	{ name: 'San Jose Giants', lat:37.320556 , long:-121.862222 , city: 'San Jose', state:'CA', stadium: 'San Jose Municipal Stadium', est:1962 , affiliation:'San Francisco Giants' , league:'California League', level:'A'},
	{ name: 'Stockton Ports', lat:37.954856 , long:-121.297956 , city: 'Stockton', state:'CA', stadium: 'Banner Island Ballpark', est:1941 , affiliation:'Oakland Athletics' , league:'California League', level:'A'},
	{ name: 'Visalia Rawhide', lat:36.3325 , long:-119.304722 , city: 'Visalia', state:'CA', stadium: 'Recreation Park', est:1946 , affiliation:'Arizona Diamondbacks' , league:'California League', level:'A'},
	{ name: 'High Desert Mavericks', lat:34.554843 , long:-117.401758 , city: 'Adelanto', state:'CA', stadium: 'Heritage Field at Stater Bros. Stadium', est:1988, affiliation:'Texas Rangers' , league:'California League', level:'A'},
	{ name: 'Inland Empire 66ers', lat:34.097222 , long:-117.295278 , city: 'San Bernadino', state:'CA', stadium: 'San Manuel Stadium', est:1941 , affiliation:'Los Angeles Angels of Anaheim' , league:'California League', level:'A'},
	{ name: 'Lake Elsinore Storm', lat:33.654167 , long:-117.301944 , city: 'Lake Elsinore', state:'CA', stadium: 'Lake Elsinore Diamond', est:1994 , affiliation:'San Diego Padres' , league:'California League', level:'A'},
	{ name: 'Lancaster JetHawks', lat:34.702811 , long:-118.172972 , city: 'Lancaster', state:'CA', stadium: 'The Hangar', est:1955 , affiliation:'Houston Astros' , league:'California League', level:'A'},
	{ name: 'Rancho Cucamonga Quakes', lat:34.102765 , long:-117.54797 , city: 'Rancho Cucamonga', state:'CA', stadium: 'LoanMart Field', est:1966 , affiliation:'Los Angeles Dodgers' , league:'California League', level:'A'},

	{ name: 'Frederick Keys', lat:39.401389 , long:-77.413333 , city: 'Frederick', state:'MD', stadium: 'Harry Grove Stadium', est:1989 , affiliation:'Baltimore Orioles' , league:'Carolina League', level:'A'},
	{ name: 'Lynchburg Hillcats', lat:37.392816 , long:-79.165623 , city: 'Lynchburg', state:'VA', stadium: 'Calvin Valwell Field', est:1963 , affiliation:'Cleveland Indians' , league:'Carolina League', level:'A'},
	{ name: 'Potomac Nationals', lat:38.684167 , long:-77.3525 , city: 'Wodbridge', state:'VA', stadium: 'G. Richard Pfitzner Stadium', est:1978 , affiliation:'Washington Nationals' , league:'Carolina League', level:'A'},
	{ name: 'Wilmington Blue Rocks', lat:39.732222 , long:-75.564444 , city: 'Wilmington', state:'DE', stadium: 'Daniel S. Frawley Stadium', est:1993 , affiliation:'Kansas City Royals' , league:'Carolina League', level:'A'},
	{ name: 'Carolina Mudcats', lat:35.817222 , long:-78.27 , city: 'Zebulon', state:'NC', stadium: 'Five County Stadium', est:1978 , affiliation:'Atlanta Braves' , league:'Carolina League', level:'A'},
	{ name: 'Myrtle Beach Pelicans', lat:33.711682 , long:-78.8845 , city: 'Myrtle Beach', state:'SC', stadium: 'TicketReturn.Com Field at Pelicans Ballpark', est:1999 , affiliation:'Chicago Cubs' , league:'Carolina League', level:'A'},
	{ name: 'Salem Red Sox', lat:37.285278 , long:-80.036667, city: 'Salem', state:'VA', stadium: 'Lewis-Gale Fiel', est:1968 , affiliation:'Boston Red Sox' , league:'Carolina League', level:'A'},
	{ name: 'Winston-Salem Dash', lat:36.091602 , long:-80.255962 , city: 'Winston-Salem', state:'NC', stadium: 'BB&T Ballpark', est:1945 , affiliation:'Chicago White Sox' , league:'Carolina League', level:'A'},

	{ name: 'Brevard County Manatees', lat:28.256944 , long:-80.739444 , city: 'Viera', state:'FL', stadium: 'Space Coast Stadium', est:1994 , affiliation:'Milwaukee Brewers' , league:'Florida State League', level:'A'},
	{ name: 'Clearwater Threshers', lat:27.971667 , long:-82.731667 , city: 'Clearwater', state:'FL', stadium: 'Bright House Field', est:1985 , affiliation:'Philidelphia Phillies' , league:'Florida State League', level:'A'},
	{ name: 'Daytona Tortugas', lat:29.2100769 , long:-81.016189 , city: 'Daytona', state:'FL', stadium: 'Jackie Robison Ballpark', est:1993 , affiliation:'Cincinnati Reds' , league:'Florida State League', level:'A'},
	{ name: 'Dunedin Blue Jays', lat:28.003611 , long:-82.786389 , city: 'Dunedin', state:'FL', stadium: 'Auto Exchange Stadium', est:1987 , affiliation:'Toronto Blue Jays' , league:'Florida State League', level:'A'},
	{ name: 'Lakeland Flying Tigers', lat:28.074722 , long:-81.950833 , city: 'Lakeland', state:'FL', stadium: 'Joker Merchant Stadium', est:1960 , affiliation:'Detroit Tigers' , league:'Florida State League', level:'A'},
	{ name: 'Tampa Yankees', lat:27.980278 , long:-82.506667 , city: 'Tampa', state:'FL', stadium: 'George M. Steinbrenner Field', est:1994 , affiliation:'New York Yankees' , league:'Florida State League', level:'A'},
	{ name: 'Bradenton Marauders', lat:27.485833 , long:-82.570278 , city: 'Bradenton', state:'FL', stadium: 'McKechnie Field', est:2010 , affiliation:'Pittsburgh Pirates' , league:'Florida State League', level:'A'},
	{ name: 'Charlotte Stone Crabs', lat:26.999167 , long:-82.181667 , city: 'Charlotte', state:'FL', stadium: 'Charlotte Sports Park', est:1980 , affiliation:'Tampa Bay Rays' , league:'Florida State League', level:'A'},
	{ name: 'Fort Myers Miracle', lat:26.538333 , long:-81.841944 , city: 'Fort Myers', state:'FL', stadium: 'Hammond Stadium', est:1926 , affiliation:'Minnesota Twins' , league:'Florida State League', level:'A'},
	{ name: 'Jupiter Hammerheads', lat:26.891111 , long:-80.116389 , city: 'Jupiter', state:'FL', stadium: 'Roger Dean Stadium', est:1965 , affiliation:'Miami Marlins' , league:'Florida State League', level:'A'},
	{ name: 'Palm Beach Cardinals', lat:26.891111 , long:-80.116389 , city: 'Jupiter', state:'FL', stadium: 'Roger Dean Stadium', est:2003 , affiliation:'St. Louis Cardinals' , league:'Florida State League', level:'A'},
	{ name: 'St. Lucie Mets', lat:27.325281 , long:-80.404494 , city: 'Port St. Lucie', state:'FL', stadium: 'Tradition Field', est:1988 , affiliation:'New York Mets' , league:'Florida State League', level:'A'},

	{ name: 'Bowling Green Hot Rods', lat:36.996778 , long:-86.440906 , city: 'Bowling Green', state:'KY', stadium: 'Bowling Green Ballpark', est:2009 , affiliation:'Tampa Bay Rays' , league:'Midwest League', level:'A'},
	{ name: 'Dayton Dragons', lat:39.764167 , long:-84.185 , city: 'Dayton', state:'OH', stadium: 'Fifth Third Field', est:1988 , affiliation:'Cincinnati Reds' , league:'Midwest League', level:'A'},
	{ name: 'Fort Wayne TinCaps', lat:41.074056 , long:-85.142861 , city: 'Fort Wayne', state:'IN', stadium: 'Parkview Field', est:2009 , affiliation:'San Diego Padres' , league:'Midwest League', level:'A'},
	{ name: 'Great Lakes Loons', lat:43.609169 , long:-84.236703 , city: 'Midland', state:'MI', stadium: 'Dow Diamond', est:1982 , affiliation:'Los Angeles Dodgers' , league:'Midwest League', level:'A'},
	{ name: 'Lake County Captains', lat:41.641111 , long:-81.435556 , city: 'Eastlake', state:'OH', stadium: 'Classic Park', est:1991 , affiliation:'Cleveland Indians' , league:'Midwest League', level:'A'},
	{ name: 'Lansing Lugnuts', lat:42.734722 , long:-84.545278 , city: 'Lansing', state:'MI', stadium: 'Cooley Law School Stadium', est:1955 , affiliation:'Toronto Blue Jays' , league:'Midwest League', level:'A'},
	{ name: 'South Bend Cubs', lat:41.670394 , long:-86.255478 , city: 'South Bend', state:'IN', stadium: 'Four Winds Field at Coveleski Stadium', est:1988 , affiliation:'Chicago Cubs' , league:'Midwest League', level:'A'},
	{ name: 'West Michigan Whitecaps', lat:43.040195 , long:-85.659832 , city: 'Comstock Park', state:'MI', stadium: 'Fifth Third Ballpark', est:1994 , affiliation:'Detroit Tigers' , league:'Midwest League', level:'A'},
	{ name: 'Beloit Snappers', lat:42.5349821 , long:-89.0086655 , city: 'Beloit', state:'WI', stadium: 'Pohlman Field', est:1982 , affiliation:'Oakland Athletics' , league:'Midwest League', level:'A'},
	{ name: 'Burlington Bees', lat:40.827555 , long:-91.136903 , city: 'Burlington', state:'IA', stadium: 'Community Field', est:1924 , affiliation:'Los Angeles Angels of Anaheim' , league:'Midwest League', level:'A'},
	{ name: 'Cedar Rapids Kernels', lat:41.9677464 , long:-91.6873377 , city: 'Cedar Rapids', state:'IA', stadium: 'Veterans Memorial Stadium', est:1890 , affiliation:'Minnesota Twins' , league:'Midwest League', level:'A'},
	{ name: 'Clinton LumberKings', lat:41.849265 , long:-90.185394 , city: 'Clinton', state:'IA', stadium: 'Ashford University Field', est:1954 , affiliation:'Seattle Mariners' , league:'Midwest League', level:'A'},
	{ name: 'Kane County Cougars', lat:41.88065 , long:-88.281756 , city: 'Geneva', state:'IL', stadium: 'Fifth Third Bank Ballpark', est:1991 , affiliation:'Arizona Diamondbacks' , league:'Midwest League', level:'A'},
	{ name: 'Peoria Chiefs', lat:40.6875 , long:-89.5975 , city: 'Peoria', state:'IL', stadium: 'Dozer Park', est:1983 , affiliation:'St. Louis Cardinals' , league:'Midwest League', level:'A'},
	{ name: 'Quad Cities River Bandits', lat:41.518669 , long:-90.582242 , city: 'Davenport', state:'IA', stadium: 'Modern Woodmen Park', est:1901 , affiliation:'Houston Astros' , league:'Midwest League', level:'A'},
	{ name: 'Wisconsin Timber Rattlers', lat:44.283524 , long:-88.468742 , city: 'Appleton', state:'WI', stadium: 'Neuroscience Group Field at Fox Cities Stadium', est:1891 , affiliation:'Milwaukee Brewers' , league:'Midwest League', level:'A'},

	{ name: 'Delmarva Shorebirds', lat:38.369722 , long:-75.529444 , city: 'Salisbury', state:'MD', stadium: 'Arthur W. Perdue Stadium', est:1991 , affiliation:'Baltimore Orioles' , league:'South Atlantic League', level:'A'},
	{ name: 'Greensboro Grasshoppers', lat:36.076667 , long:-79.794722 , city: 'Greensboro', state:'NC', stadium: 'NewBridge Bank Park', est:1979 , affiliation:'Miami Marlins' , league:'South Atlantic League', level:'A'},
	{ name: 'Hagerstown Suns', lat:39.632778 , long:-77.7125 , city: 'Hagerston', state:'MD', stadium: 'Municipal Stadium', est:1981 , affiliation:'Washington Nationals' , league:'South Atlantic League', level:'A'},
	{ name: 'Hickory Crawdads', lat:35.749167 , long:-81.378611 , city: 'Hickory', state:'NC', stadium: 'L. P. Frans Stadium', est:1993 , affiliation:'Texas Rangers' , league:'South Atlantic League', level:'A'},
	{ name: 'Kannapolis Intimidators', lat:35.507778 , long:-80.566389 , city: 'Kannapolis', state:'NC', stadium: 'CMC-NorthEast Stadium', est:1995 , affiliation:'Chicago White Sox' , league:'South Atlantic League', level:'A'},
	{ name: 'Lakewood BlueClaws', lat:40.075278 , long:-74.186667 , city: 'Lakewood', state:'NJ', stadium: 'FirstEnergy Park', est:1987 , affiliation:'Philidelphia Phillies' , league:'South Atlantic League', level:'A'},
	{ name: 'West Virginia Power', lat:38.349028 , long:-81.625111 , city: 'Charleston', state:'WV', stadium: 'Appalachian Power Park', est:1987 , affiliation:'Pittsburgh Pirates' , league:'South Atlantic League', level:'A'},
	{ name: 'Asheville Tourists', lat:35.587222 , long:-82.549167 , city: 'Asheville', state:'NC', stadium: 'McCormick Field', est:1897 , affiliation:'Colorado Rockies' , league:'South Atlantic League', level:'A'},
	{ name: 'Augusta GreenJackets', lat:33.495 , long:-82.000556 , city: 'Augusta', state:'GA', stadium: 'Lake Olmstead Stadium', est:1980 , affiliation:'San Francsisco Giants' , league:'South Atlantic League', level:'A'},
	{ name: 'Charleston RiverDogs', lat:32.790278 , long:-79.961111 , city: 'Charleston', state:'SC', stadium: 'Joseph P. Riley, Jr. Park', est:1980 , affiliation:'New York Yankees' , league:'South Atlantic League', level:'A'},
	{ name: 'Greenville Drive', lat:34.8422 , long:-82.4082 , city: 'Greenville', state:'SC', stadium: 'Fluor Field at the West End', est:1977 , affiliation:'Boston Red Sox' , league:'South Atlantic League', level:'A'},
	{ name: 'Lexington Legends', lat:38.06545 , long:-84.47852 , city: 'Lexington', state:'KY', stadium: 'Whitaker Bank Ballpark', est:2001 , affiliation:'Kansas City Royals' , league:'South Atlantic League', level:'A'},
	{ name: 'Rome Braves', lat:34.285833 , long:-85.167222 , city: 'Rome', state:'GA', stadium: 'State Mutual Stadium', est:2003 , affiliation:'Atlanta Braves' , league:'South Atlantic League', level:'A'},
	{ name: 'Savannah Sand Gnats', lat:32.044722 , long:-81.078889 , city: 'Savannah', state:'GA', stadium: 'Grayson Stadium', est:1984 , affiliation:'New York Mets' , league:'South Atlantic League', level:'A'},

	{ name: 'Aberdeen IronBirds', lat:39.530873 , long:-76.185985 , city: 'Aberdeen', state:'MD', stadium: 'Leidos Field at Ripken Stadium', est:1977 , affiliation:'Baltimore Orioles' , league:'New York-Penn League', level:'A'},
	{ name: 'Brooklyn Cyclones', lat:40.574547 , long:-73.984353 , city: 'Brooklyn', state:'NY', stadium: 'MCU Park', est:1986 , affiliation:'New York Mets' , league:'New York-Penn League', level:'A'},
	{ name: 'Hudson Valley Renegades', lat:41.527911 , long:-73.961067 , city: 'Wappinger Falls', state:'NY', stadium: 'Dutchess Stadium', est:1983 , affiliation:'Tampa Bay Rays' , league:'New York-Penn League', level:'A'},
	{ name: 'Staten Island Yankees', lat:40.645575 , long:-74.076428 , city: 'Staten Island', state:'NY', stadium: 'Richmond County Bank Ballpark', est:1999 , affiliation:'New York Yankees' , league:'New York-Penn League', level:'A'},
	{ name: 'Auburn Doubledays', lat:42.9416 , long:-76.585232 , city: 'Auburn', state:'NY', stadium: 'Falcon Park', est:1958 , affiliation:'Washington Nationals' , league:'New York-Penn League', level:'A'},
	{ name: 'Batavia Muckdogs', lat:43.009174 , long:-78.178722 , city: 'Batavia', state:'NY', stadium: 'Dwyer Stadium', est:1939 , affiliation:'Miami Marlins' , league:'New York-Penn League', level:'A'},
	{ name: 'Mahoning Valley Scrappers', lat:41.218453 , long:-80.755241 , city: 'Niles', state:'Ohio', stadium: 'Eastwood Field', est:1999 , affiliation:'Cleveland Indians' , league:'New York-Penn League', level:'A'},
	{ name: 'State College Spikes', lat:40.811944 , long:-77.850833 , city: 'University Park', state:'PA', stadium: 'Medlar Field at Lubrano Park', est:1981 , affiliation:'St. Louis Cardinals' , league:'New York-Penn League', level:'A'},
	{ name: 'West Virginia Black Bears', lat:39.64473 , long:-79.995838 , city: 'Morgantown', state:'WV', stadium: 'Monongalia County Ballpark', est:2015 , affiliation:'Pittsburgh Pirates' , league:'New York-Penn League', level:'A'},
	{ name: 'Williamsport Crosscutters', lat:41.242347 , long:-77.047067 , city: 'Williamsport', state:'PA', stadium: 'Susquehanna Bank Park at Historic Bowman Field', est:1993 , affiliation:'Philidelphia Phillies' , league:'New York-Penn League', level:'A'},
	{ name: 'Connecticut Tigers', lat:41.573875 , long:-72.107072 , city: 'Norwich', state:'CT', stadium: 'Senator Thomas J. Dodd Memorial Stadium', est:1942 , affiliation:'Detroit Tigers' , league:'New York-Penn League', level:'A'},
	{ name: 'Lowell Spinners', lat:42.65327 , long:-71.318114 , city: 'Lowell', state:'MA', stadium: 'Edward A. LeLacheur Park', est:1996 , affiliation:'Boston Red Sox' , league:'New York-Penn League', level:'A'},
	{ name: 'Tri-City ValleyCats', lat:42.695329 , long:-73.680464 , city: 'Troy', state:'NY', stadium: 'Joseph L. Bruno Stadium', est:1977 , affiliation:'Houston Astros' , league:'New York-Penn League', level:'A'},
	{ name: 'Vermont Lake Monsters', lat:44.481656 , long:-73.187656 , city: 'Burlington', state:'VT', stadium: 'Centennial Field', est:1977 , affiliation:'Oakland Athletics' , league:'New York-Penn League', level:'A'},

	{ name: 'Everett AquaSox', lat:47.965949 , long:-122.2019705 , city: 'Everett', state:'WA', stadium: 'Everett Memorial Stadium', est:1984 , affiliation:'Seattle Mariners' , league:'Northwest League', level:'A'},
	{ name: 'Spokane Indians', lat:47.662 , long:-117.345 , city: 'Spokane', state:'WA', stadium: 'Avista Stadium', est:1890 , affiliation:'Texas Rangers' , league:'Northwest League', level:'A'},
	{ name: 'Tri-City Dust Devils', lat:46.267106 , long:-119.172006 , city: 'Pasco', state:'WA', stadium: 'Gesa Stadium', est:2001 , affiliation:'San Diego Padres' , league:'Northwest League', level:'A'},
	{ name: 'Vancouver Canadians', lat:49.2431 , long:-123.1063 , city: 'Vancouver', state:'BC', stadium: 'Scotiabank Field at Nat Bailey Stadium', est:2000 , affiliation:'Toronto Blue Jays' , league:'Northwest League', level:'A'},
	{ name: 'South Boise Hawks', lat:43.656 , long:-116.279 , city: 'Boise', state:'ID', stadium: 'Memorial Stadium', est:1987 , affiliation:'Colorado Rockies' , league:'Northwest League', level:'A'},
	{ name: 'Eugene Emeralds', lat:44.059 , long:-123.066 , city: 'Eugene', state:'OR', stadium: 'PK Park', est:1955 , affiliation:'Chicago Cubs' , league:'Northwest League', level:'A'},
	{ name: 'Hillsboro Hops', lat:45.5536 , long:-122.9082 , city: 'Hillsboro', state:'OR', stadium: 'Ron Tonkin Field', est:1977 , affiliation:'Arizona Diamondbacks' , league:'Northwest League', level:'A'},
	{ name: 'Salem-Keizer Volcanoes', lat:45.015075 , long:-122.994011 , city: 'Keizer', state:'OR', stadium: 'Volcanoes Stadium', est:1997 , affiliation:'San Francisco Giants' , league:'Northwest League', level:'A'},

	{ name: 'Bluefield Blue Jays', lat:37.249444 , long:-81.246389 , city: 'Bluefield', state:'WV', stadium: 'Bowen Field', est:1937 , affiliation:'Toronto Blue Jays' , league:'Appalachian League', level:'Rookie'},
	{ name: 'Burlington Royals', lat:36.088056 , long:-79.408333 , city: 'Burlington', state:'NC', stadium: 'Burlington Athletic Stadium', est:1986 , affiliation:'Kansas City Royals' , league:'Appalachian League', level:'Rookie'},
	{ name: 'Danville Braves', lat:36.575833 , long:-79.3725 , city: 'Danville', state:'VA', stadium: 'American Legion Field', est:1993 , affiliation:'Atlanta Braves' , league:'Appalachian League', level:'Rookie'},
	{ name: 'Princeton Rays', lat:37.358333 , long:-81.105278 , city: 'Princeton', state:'WV', stadium: 'H. P. Hunnicutt Field', est:1988 , affiliation:'Tampa Bay Rays' , league:'Appalachian League', level:'Rookie'},
	{ name: 'Pulaski Yankees', lat:37.039306 , long:-80.775556 , city: 'Pulaski', state:'VA', stadium: 'Calfee Park', est:1942 , affiliation:'New York Yankees' , league:'Appalachian League', level:'Rookie'},
	{ name: 'Bristol Pirates', lat:36.601968 , long:-82.199251 , city: 'Bristol', state:'VA', stadium: 'Boyce Cox Field at DeVault Memorial Stadium', est:1969 , affiliation:'Pittsburgh Pirates' , league:'Appalachian League', level:'Rookie'},
	{ name: 'Elizabethton Twins', lat:36.354899 , long:-82.232183 , city: 'Elizabethton', state:'VA', stadium: "Joe O'Brien Field", est:1974 , affiliation:'Minnesota Twins' , league:'Appalachian League', level:'Rookie'},
	{ name: 'Greeneville Astros', lat:36.173149 , long:-82.756115 , city: 'Greeneville', state:'TN', stadium: 'Pioneer Park', est:1988 , affiliation:'Houston Astros' , league:'Appalachian League', level:'Rookie'},
	{ name: 'Johnson City Cardinals', lat:36.318611 , long:-82.340833 , city: 'Johnson City', state:'TN', stadium: 'Howard Johnson Field', est:1937 , affiliation:'St. Louis Cardinals' , league:'Appalachian League', level:'Rookie'},
	{ name: 'Kingsport Mets', lat:36.562778 , long:-82.598611 , city: 'Kingsport', state:'TN', stadium: 'Hunter Wright Stadium', est:1921 , affiliation:'New York Mets' , league:'Appalachian League', level:'Rookie'},

	{ name: 'Billings Mustangs', lat:45.790278 , long:-108.511111 , city: 'Billings', state:'MT', stadium: 'Dehler Park', est:1948 , affiliation:'Cincinnati Reds' , league:'Pioneer League', level:'Rookie'},
	{ name: 'Great Falls Voyagers', lat:47.516919 , long:-111.259467 , city: 'Great Falls', state:'MT', stadium: 'Centene Stadium', est:1969 , affiliation:'Chicago White Sox' , league:'Pioneer League', level:'Rookie'},
	{ name: 'Helena Brewers', lat:46.599167 , long:-112.027222 , city: 'Helena', state:'MT', stadium: 'Kindrick Legion Field', est:1978 , affiliation:'Milwaukee Brewers' , league:'Pioneer League', level:'Rookie'},
	{ name: 'Missoula Osprey', lat:46.873431 , long:-114.007294 , city: 'Missoula', state:'MT', stadium: 'Ogren Park at Allegiance Field', est:1987 , affiliation:'Arizona Diamondbacks' , league:'Pioneer League', level:'Rookie'},
	{ name: 'Grand Junction Rockies', lat:39.076684 , long:-108.550404 , city: 'Grand Junction', state:'CO', stadium: 'Suplizio Field', est:1978 , affiliation:'Colorado Rockies' , league:'Pioneer League', level:'Rookie'},
	{ name: 'Idaho Falls Chukars', lat:43.505161 , long:-112.037861 , city: 'Idaho Falls', state:'ID', stadium: 'Melaleuca Field', est:1940 , affiliation:'Kansas City Royals' , league:'Pioneer League', level:'Rookie'},
	{ name: 'Ogden Raptors', lat:41.223779 , long:-111.974845 , city: 'Ogden', state:'UT', stadium: 'Lindquist Field', est:1977 , affiliation:'Los Angeles Dodgers' , league:'Pioneer League', level:'Rookie'},
	{ name: 'Orem Owlz', lat:40.276874 , long:-111.717234 , city: 'Orem', state:'UT', stadium: 'Brent Brown Ballpark', est:2001 , affiliation:'Los Angeles Angels of Anaheim' , league:'Pioneer League', level:'Rookie'},

	{ name: 'Arizona League Angels', lat:33.400556 , long:-111.969722 , city: 'Tempe', state:'AZ', stadium: 'Tempe Diablo Stadium', est:1989 , affiliation:'Los Angeles Angels of Anaheim' , league:'Arizona League', level:'Rookie'},
	{ name: 'Arizona League Athletics', lat:33.428285 , long:-111.829762 , city: 'Mesa', state:'AZ', stadium: 'Fitch Park', est:1988 , affiliation:'Oakland Athletics' , league:'Arizona League', level:'Rookie'},
	{ name: 'Arizona League Brewers', lat:33.492222 , long:-112.173056 , city: 'Phoenix', state:'AZ', stadium: 'Maryvale Stadium', est:1988 , affiliation:'Milwaukee Brewers' , league:'Arizona League', level:'Rookie'},
	{ name: 'Arizona League Cubs', lat:33.4313 , long:-111.8816 , city: 'Mesa', state:'AZ', stadium: 'Sloan Park', est:1997 , affiliation:'Chicago Cubs' , league:'Arizona League', level:'Rookie'},
	{ name: 'Arizona League Diamondbacks', lat:33.546111 , long:-111.885278 , city: 'Scottsdale', state:'AZ', stadium: 'Salt River Fields at Talking Stick', est:2011 , affiliation:'Arizona Diamondbacks' , league:'Arizona League', level:'Rookie'},
	{ name: 'Arizona League Dodgers', lat:33.514167 , long:-112.295833 , city: 'Glendale', state:'AZ', stadium: 'Camelback Ranch', est:1983 , affiliation:'Los Angeles Dodgers' , league:'Arizona League', level:'Rookie'},
	{ name: 'Arizona League Giants', lat:33.488333 , long:-111.921111 , city: 'Scottsdale', state:'AZ', stadium: 'Scottsdale', est:2005 , affiliation:'San Francisco Giants' , league:'Arizona League', level:'Rookie'},
	{ name: 'Arizona League Indians', lat:33.429167 , long:-112.39 , city: 'Goodyear', state:'AZ', stadium: 'Goodyear Ballpark', est:2009 , affiliation:'Cleveland Indians' , league:'Arizona League', level:'Rookie'},
	{ name: 'Arizona League Mariners', lat:33.6319 , long:-112.2332 , city: 'Peoria', state:'AZ', stadium: 'Peoria Sports Complex', est:1988 , affiliation:'Seattle Mariners' , league:'Arizona League', level:'Rookie'},
	{ name: 'Arizona League Padres', lat:33.6319 , long:-112.2332 , city: 'Peoria', state:'AZ', stadium: 'Peoria Sports Complex', est:1988 , affiliation:'San Diego Padres' , league:'Arizona League', level:'Rookie'},
	{ name: 'Arizona League Rangers', lat:33.627778 , long:-112.377778 , city: 'Surprise', state:'AZ', stadium: 'Surprise Stadium', est:2003 , affiliation:'Texas Rangers' , league:'Arizona League', level:'Rookie'},
	{ name: 'Arizona League Reds', lat:33.429167 , long:-112.39 , city: 'Goodyear', state:'AZ', stadium: 'Goodyear Ballpark', est:2010 , affiliation:'Cincinnati Reds' , league:'Arizona League', level:'Rookie'},
	{ name: 'Arizona League Royals', lat:33.627778 , long:-112.377778 , city: 'Surprise', state:'AZ', stadium: 'Surprise Stadium', est:2003 , affiliation:'Kansas City Royals' , league:'Arizona League', level:'Rookie'},
	{ name: 'Arizona League White Sox', lat:33.514167 , long:-112.295833, city: 'Glendale', state:'AZ', stadium: 'Camelback Ranch', est:1998 , affiliation:'Chicago White Sox' , league:'Arizona League', level:'Rookie'},

	{ name: 'GCL Cardinals', lat:26.891111 , long:-80.116389 , city: 'Jupiter', state:'FL', stadium: 'Roger Dean Stadium', est:1963 , affiliation:'St. Louis Cardinals' , league:'Gulf Coast League', level:'Rookie'},
	{ name: 'GCL Marlins', lat:26.891111 , long:-80.116389 , city: 'Jupiter', state:'FL', stadium: 'Roger Dean Stadium', est:1992 , affiliation:'Miami Marlins' , league:'Gulf Coast League', level:'Rookie'},
	{ name: 'GCL Mets', lat:27.325281 , long:-80.404494 , city: 'Port St. Lucie', state:'FL', stadium: 'Tradition Field', est:1988 , affiliation:'New York Mets' , league:'Gulf Coast League', level:'Rookie'},
	{ name: 'GCL Nationals', lat:28.256944 , long:-80.739444 , city: 'Viera', state:'FL', stadium: 'Washington Nationals Training Complex, Space Coast Stadium', est:1969 , affiliation:'Washington National' , league:'Gulf Coast League', level:'Rookie'},
	{ name: 'GCL Astros', lat:28.298333 , long:-81.363889 , city: 'Kissimmee', state:'FL', stadium: 'Osceola County Stadium', est:1977 , affiliation:'Houston Astros' , league:'Gulf Coast League', level:'Rookie'},
	{ name: 'GCL Braves', lat:28.337083 , long:-81.556 , city: 'Lake Buena Vista', state:'FL', stadium: 'Champion Stadium', est:1964 , affiliation:'Atlanta Braves' , league:'Gulf Coast League', level:'Rookie'},
	{ name: 'GCL Tigers', lat:28.074722 , long:- 81.950833, city: 'Lakeland', state:'FL', stadium: 'Joker Marchant Stadium', est:1995 , affiliation:'Detroit Tigers' , league:'Gulf Coast League', level:'Rookie'},
	{ name: 'GCL Yankees 2', lat:27.980278 , long:-82.506667 , city: 'Tampa', state:'FL', stadium: 'George M. Steinbrenner Field', est:2000 , affiliation:'New York Yankees' , league:'Gulf Coast League', level:'Rookie'},
	{ name: 'GCL Blue Jays', lat:28.030735 , long:-82.75685229999999 , city: 'Dunedin', state:'FL', stadium: 'Bobby Mattick Training Center at Englebert Complex', est:1981 , affiliation:'Toronto Blue Jays' , league:'Gulf Coast League', level:'Rookie'},
	{ name: 'GCL Phillies', lat:27.971667 , long:-82.731667 , city: 'Clearwater', state:'FL', stadium: 'Carpenter Complex', est:1984 , affiliation:'Philadelphia Phillies' , league:'Gulf Coast League', level:'Rookie'},
	{ name: 'GCL Pirates', lat:27.482598 , long:-82.528235 , city: 'Bradenton', state:'FL', stadium: 'Pirate City', est:1968 , affiliation:'Pittsburgh Pirates' , league:'Gulf Coast League', level:'Rookie'},
	{ name: 'GCL Yankees 1', lat:27.980278 , long:-82.506667 , city: 'Tampa', state:'FL', stadium: 'George M. Steinbrenner Field', est:2000 , affiliation:'New York Yankees' , league:'Gulf Coast League', level:'Rookie'},
	{ name: 'GCL Orioles', lat:27.347778 , long:-82.517222 , city: 'Sarasota', state:'FL', stadium: 'Ed Smith Stadium', est:1991 , affiliation:'Baltimore Orioles' , league:'Gulf Coast League', level:'Rookie'},
	{ name: 'GCL Rays', lat:26.999167 , long:-82.181667 , city: 'Charlotte', state:'FL', stadium: 'Charlotte Sports Park', est:1996 , affiliation:'Tampa Bay Rays' , league:'Gulf Coast League', level:'Rookie'},
	{ name: 'GCL Red Sox', lat:26.548056 , long:-81.763333 , city: 'Fort Myers', state:'FL', stadium: 'JetBlue Park at Fenway South', est:1992 , affiliation:'Boston Red Sox' , league:'Gulf Coast League', level:'Rookie'},
	{ name: 'GCL Twins', lat:26.538333 , long:-81.841944 , city: 'Fort Myers', state:'FL', stadium: 'Lee County Sports Complex', est:1991 , affiliation:'Minnesota Twins' , league:'Gulf Coast League', level:'Rookie'},

	//{ name: '', lat: , long:- , city: '', state:'', stadium: '', est: , affiliation:'' , league:'', level:'Rookie'},
];

/* LANDMARK LOCATIONS */
var places = [
  { name: "Forbes Field", lat:40.441944 , long:-79.954167 , city: 'Pittsburgh', state:'PA', standing:false, type:'stadium', description:"Third stadium for the Pittsburgh Pirates, as well as the first for the Steelers. Parts of the Stadium still stand, around which fans gather annually to remember Bill Mazeroski's HR that won the 1960 World Series.", link:"https://en.wikipedia.org/wiki/Forbes_Field"},
	{ name: "Huntington Avenue Grounds", lat:42.338889 , long:-71.088889 , city: 'Boston', state:'MA', standing:false, type:'stadium', description:"First home for the Boston Red Sox, these grounds held the first interleague World Series, as well as the first modern-era perfect game (thrown by Cy Young).", link:"https://en.wikipedia.org/wiki/Huntington_Avenue_Grounds"},
	{ name: "Field of Dreams", lat:42.497778 , long:-91.055 , city: 'Dyersville', state:'IA', standing:true, type:'movie', description:"Filming location for the 1989 film 'Field of Dreams', a baseball classic starring Kevin Costner.", link:"https://en.wikipedia.org/wiki/Field_of_Dreams_(Dubuque_County,_Iowa)"},
	{ name: "Babe Ruth's Grave", lat:41.0961463 , long:-73.793575 , city: 'Hawthorne', state:'NY', standing:true, type:'landmark', description:"The grave of George Herman Ruth Jr., the Great Bambino, Babe Ruth.", link:"http://m.mlb.com/news/article/67494458/babe-ruths-gravesite-remains-destination-for-faithful-fans"},
	{ name: "Ebbets Field", lat:40.665 , long:-73.958056 , city: 'Brooklyn', state:'NY', standing:false, type:'stadium', description:"Home of the Brooklyn Dodgers from 1913 to 1957.", link:"https://en.wikipedia.org/wiki/Ebbets_Field"},
	{ name: "Polo Grounds", lat:40.830833 , long:-73.9375 , city: 'Manhattan', state:'NY', standing:false, type:'stadium', description:"Home to a variety of baseball teams, including the Yankees, the Metropolitans, and the Giants.", link:"https://en.wikipedia.org/wiki/Polo_Grounds"},
	{ name: "National Baseball Hall of Fame and Museum", lat:42.700322 , long:-74.92369 , city: 'Cooperstown', state:'NY', standing:true, type:'museum', description:"The Hall of Fame houses baseball's greatest artifacts and memoribilia, honors the sport's legends, and teaches its history to hundreds of thousands of visitors each year.", link:"http://baseballhall.org"},
	{ name: "National Baseball Hall of Fame and Museum", lat:42.700322 , long:-74.92369 , city: 'Cooperstown', state:'NY', standing:true, type:'museum', description:"The Hall of Fame houses baseball's greatest artifacts and memoribilia, honors the sport's legends, and teaches its history to hundreds of thousands of visitors each year.", link:"http://baseballhall.org"},
  { name: "Elysian Fields", lat:40.74995 , long:-74.02737 , city: 'Hoboken', state:'NJ', standing:false, type:'stadium', description:"It is said that the first organized baseball game was played here in 1846. A bronze plaque lies today where the 1st base line once was.", link:"https://en.wikipedia.org/wiki/Elysian_Fields,_Hoboken,_New_Jersey"},
	{ name: "Negro Leagues Baseball Museum", lat:39.0914 , long:-94.5627 , city: 'Kansas City', state:'MO', standing:true, type:'museum', description:"Founded in 1990, this is a privately funded museum offering visitors a chance to learn about the history of Negro League Baseball in the US.", link:"https://www.nlbm.com"},

	//{ name: "", lat: , long:- , city: '', state:'', standing:, type:'', description:"", link:""},
];
